apiVersion : v1
data :
   prometheus.yml : |
      # my global config
      global:
        scrape_interval:     15s
        evaluation_interval: 15s 
      alerting:
        alertmanagers:
        - static_configs:
          - targets:
      rule_files:
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
          - targets: ['localhost:9090']
        - job_name: 'node1'
          - targets: ['192.168.101.202:9100']
kind : ConfigMap
metadata :
  name : prom-config

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    name: myprom
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myprom
  template:
    metadata:
      name: myprom
      labels:
        name: myprom
    spec:
      containers:
      - name: mypromethus-con
        image: vimal13/prometheus
        volumeMounts :
            - name : configs
              mountPath : /etc/prometheus/prometheus.yml
              subPath : prometheus.yml
            - name : prom-pvc
              mountPath : /prometheus
      volumes :
      - name : configs
        configMap :
          name : prom-config
      - name : prom-pvc
        persistentVolumeClaim:
          claimName: prometheus-pvc1
---

apiVersion: v1
kind: Service
metadata:
 name: myservice
 labels:
  app: myservicetesting
spec:
 selector:
  env: testing
 type: NodePort
 ports:
  - name: port1
    port: 9090
    targetPort: 9090
  - name: port2
    port: 3000
    targetPort: 3000 
